databases:
  - name: Takatou_DB
    databaseName: takatou_db
    user: Takatou
    region: singapore

services:
  - type: web
    name: Takatou_DB
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Takatou_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false